"""migration_2_add_photo_column_to_product

Revision ID: 89a59c4431d9
Revises: afd6dac4b156
Create Date: 2024-03-19 15:47:16.764026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Column, String
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "89a59c4431d9"
down_revision: Union[str, None] = "afd6dac4b156"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product") as batch_op:
        batch_op.add_column(
            sa.Column(
                name="photo", type_=sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product") as batch_op:
        batch_op.drop_column(column_name="photo")
    # ### end Alembic commands ###
