"""migration_1_add_movement

Revision ID: afd6dac4b156
Revises: e569c16f19dd
Create Date: 2024-03-17 17:28:31.543591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afd6dac4b156'
down_revision: Union[str, None] = 'e569c16f19dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('type_movement', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='movement_product_id_fkey'),
                    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='movement_supplier_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='movement_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='movement_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement')
    # ### end Alembic commands ###
